#!/bin/bash -e
# vim: set ts=4 sw=4 sts=4 et :

source /usr/lib/qubes-whonix/utility_functions.sh

if [ -e '/var/run/qubes-service/qubes-whonix-secure-proxy' ]; then
    uwtwrapper["/usr/bin/apt-get"]="0"
fi
