#!/bin/bash -e
# vim: set ts=4 sw=4 sts=4 et :

source /usr/lib/qubes-whonix/utility_functions.sh

# Files that will have the immutable bit set
# since we don't want them modified by other programs
IMMUTABLE_FILES=(
    '/etc/resolv.conf'
    '/etc/hostname'
    '/etc/hosts'
    '/etc/localtime'
    '/etc/timezone'
)

# Make sure all .anondist files in list are immutable
immutableFilesEnable "${IMMUTABLE_FILES}"
immutableFilesEnable "${IMMUTABLE_FILES}" ".anondist"

# Make sure we are using a copy of the annondist file and if not
# copy the annondist file and set it immutable
copyAnondist "/etc/resolv.conf"
copyAnondist "/etc/hosts"
copyAnondist "/etc/hostname"
copyAnondist "/etc/localtime"
copyAnondist "/etc/timezone"

if [ "${QUBES_WHONIX}" == "gateway" ] || [ "${QUBES_WHONIX}" == "workstation" ]; then
    # Replace IP addresses in known configuration files / scripts with
    # currently discovered IP address
    /usr/lib/qubes-whonix/init/replace-ips
fi

# Make sure hostname is correct
/bin/hostname host
