#!/bin/bash -e
# vim: set ts=4 sw=4 sts=4 et :

source /usr/lib/qubes-whonix/utility_functions.sh

# Location of files which contains list of protected files
PROTECTED_FILE_LIST='/var/lib/qubes/protected-files'

# Files that will marked as being protected to eliminate modification from Qubes
PROTECTED_FILES=(
    '/etc/resolv.conf'
    '/etc/hostname'
    '/etc/hosts'
    '/etc/localtime'
    '/etc/timezone'
)

# Make sure all .anondist files in list are not immutable. Fixes immutable issue
immutableFilesDisable "${PROTECTED_FILES}"
immutableFilesDisable "${PROTECTED_FILES}" ".anondist"

for protected_file in "${PROTECTED_FILES[@]}"; do
    # Enable protected services
    if ! grep -q "^${protected_file}$" "${PROTECTED_FILE_LIST}" 2>/dev/null; then
	    echo -e "${protected_file}" >> "${PROTECTED_FILE_LIST}"
    fi

    # Make sure we are using a copy of the anondist file and if not
    # copy the anondist file and set it immutable
    copyAnondist "${protected_file}"
done

if [ "${QUBES_WHONIX}" == "gateway" ] || [ "${QUBES_WHONIX}" == "workstation" ]; then
    # Replace IP addresses in known configuration files / scripts with
    # currently discovered IP address
    /usr/lib/qubes-whonix/init/replace-ips
fi

# Make sure hostname is correct
/bin/hostname host
