#!/bin/bash -e
# vim: set ts=4 sw=4 sts=4 et :

source /usr/lib/qubes-whonix/utility_functions.sh

# Make sure IP forwarding is disabled
echo "0" > /proc/sys/net/ipv4/ip_forward

if [ -e '/var/run/qubes-service/qubes-network' ]; then
    # Set interfaces for Whonix firewall
    if [ "${QUBES_WHONIX}" == "gateway" ]; then
        export INT_IF="vif+"
        export INT_TIF="vif+"
    fi

    # Load the firewall
    /usr/bin/whonix_firewall

    systemctl restart qubes-updates-proxy.service
fi
