#!/bin/bash -e
# vim: set ts=4 sw=4 sts=4 et :

#
# To umount all binds, just pass any arg in $1
#

# Don't run if started as a template
if [ -e "/var/run/qubes-service/whonix-gateway" ] || [ -e "/var/run/qubes-service/whonix-workstation" ]; then
    # Array of directories to bind
    BINDS=(
        '/rw/srv/qubes-whonix/var/cache/qubes-whonix:/var/cache/qubes-whonix'
        '/rw/srv/whonix/var/lib/whonix:/var/lib/whonix'
        '/rw/srv/whonix/var/lib/whonixcheck:/var/lib/whonixcheck'
        '/rw/srv/whonix/var/cache/whonix-setup-wizard:/var/cache/whonix-setup-wizard'
        '/rw/srv/whonix/etc/tor:/etc/tor'
    )

    for bind in ${BINDS[@]}; do
        rw_dir="${bind%%:*}"
        ro_dir="${bind##*:}"

        # Make sure ro directory is not mounted
        umount "${ro_dir}" 2> /dev/null || true

        if [ -n "${1}" ]; then
            echo "Umounting only..."
            exit 0
        fi

        # Make sure ro directory exists
        if ! [ -d "${ro_dir}" ]; then
            mkdir -p "${ro_dir}"
        fi

        # Initially copy over data directories to /rw if rw directory does not exist
        if ! [ -d "${rw_dir}" ]; then
            mkdir -p "${rw_dir}"
            rsync -hax "${ro_dir}/." "${rw_dir}"
        fi

        # Bind the directory
        sync
        mount --bind "${rw_dir}" "${ro_dir}"
    done
    sync
fi

exit 0
