#!/bin/bash -e
# vim: set ts=4 sw=4 sts=4 et :

source /usr/lib/qubes-whonix/utility_functions.sh

if ! [ "${QUBES_WHONIX}" == "template" ]; then
    sudo /usr/lib/qubes-whonix/bind-dirs
fi

if [ "${QUBES_WHONIX}" == "gateway" ]; then
    enable_sysv tor
    enable_sysv sdwdate

    if grep "^DisableNetwork 0$" /etc/tor/torrc; then
        sudo systemctl restart sdwdate
        sudo systemctl restart tor
    else
        sudo systemctl restart sdwdate
        #sudo systemctl stop tor
        sudo systemctl restart tor

        # Whonix setup complete 
        sudo mkdir -p /var/lib/whonix/do_once
        sudo touch /var/lib/whonix/do_once/whonixsetup.done

        #sudo /usr/bin/whonixsetup
        XDG_CURRENT_DESKTOP=gnome sudo /usr/bin/whonix-setup-wizard setup -style gtk+
    fi

elif [ "${QUBES_WHONIX}" == "workstation" ]; then
    enable_sysv sdwdate
    sudo systemctl restart sdwdate

    if ! [ -f "/var/lib/whonix/do_once/whonixsetup.done" ]; then
        # Whonix setup complete 
        sudo mkdir -p /var/lib/whonix/do_once
        sudo touch /var/lib/whonix/do_once/whonixsetup.done

        #sudo /usr/bin/whonixsetup
        XDG_CURRENT_DESKTOP=gnome sudo /usr/bin/whonix-setup-wizard setup -style gtk+
    fi

elif [ "${QUBES_WHONIX}" == "template" ] && [ ! -e '/var/run/qubes-service/qubes-whonix-secure-proxy' ]; then
    # Set secure defaults.
    sudo iptables -P INPUT DROP
    sudo iptables -P FORWARD DROP
    sudo iptables -P OUTPUT DROP

    # Flush old rules.
    sudo iptables -F
    sudo iptables -X
    sudo iptables -t nat -F
    sudo iptables -t nat -X
    sudo iptables -t mangle -F
    sudo iptables -t mangle -X

    # Display warning that netvm is not connected to a torvm
    /usr/lib/qubes-whonix/alert update /usr/lib/qubes-whonix/messages.yaml
fi
