#!/bin/bash -e
# vim: set ts=4 sw=4 sts=4 et :

source /usr/lib/qubes-whonix/utility_functions.sh

if [ -e /var/run/qubes-service/whonix-template ]; then

    # Display warning that TemplateVM is not connected to a Tor update proxy
    if [ ! -e '/var/run/qubes-service/whonix-secure-proxy' ]; then
        /usr/lib/qubes-whonix/alert update /usr/lib/qubes-whonix/messages.yaml
    fi

    # Setup repository
    if [ ! -e "/var/cache/whonix-setup-wizard/status-files/whonix_repository.done" ]; then
        XDG_CURRENT_DESKTOP=gnome sudo /usr/bin/whonix-setup-wizard repository -style gtk+
    fi
fi
